{{- if (include "anchore-ui.engineCreateSecret" .) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anchore-ui.engineSecretName" . }}
  labels:
    {{- include "anchore-ui.labels" . | nindent 4 }}
type: Opaque
data:
  login: {{ .Values.anchore.api.auth.login }}
  password: {{ .Values.anchore.api.auth.password }}

{{- end }}