{{- if (include "anchore-ui.uiCreateSecret" .) }}

  {{- $passwordValue := (include "anchore-ui.uiPassword" .) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "anchore-ui.fullname" .)) }}
  {{- if $secret }}
  {{- $passwordValue = index $secret.data "password" }}
  {{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anchore-ui.uiSecretName" . }}
  labels:
    {{- include "anchore-ui.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  login: {{ .Values.auth.login }}
  password: {{ $passwordValue }}

{{- end }}